[package]
name = "front"
version = "0.1.0"
authors = ["javier"]
edition = "2021"

[dependencies]
yew = "0.19"
web-sys = { version = "0.3", features = ["Event","EventTarget","InputEvent"] }
js-sys = "0.3.46"
wasm-bindgen = "0.2"
